[develop] Improve install and uninstall, pre-commit hook

diff --git a/git-commit-tagger b/git-commit-tagger
--- a/git-commit-tagger
+++ b/git-commit-tagger
@@ -229,6 +229,10 @@ function install-hooks {
   hooksDir="$(git rev-parse --git-dir)/hooks"
   printf "Repository's Hooks directory: %s\n\n" "$hooksDir"
   for file in "$HOME"/.commit-tagger/hooks/*; do
+    if [ ! -e "$file" ]; then
+      printf "Directory '%s' does not exist or does not contain any files.\nInstallation aborted.\n" "$HOME/.commit-tagger/hooks"
+      exit 1
+    fi
     fileName="$(basename "$file")"
     printf "Installing '%s'...\n" "$fileName"
     if ! cp "$file" "$hooksDir"; then
@@ -256,6 +260,10 @@ function uninstall-hooks {
   hooksDir="$(git rev-parse --git-dir)/hooks"
   printf "Repository's Hooks directory: %s\n\n" "$hooksDir"
   for file in "$HOME"/.commit-tagger/hooks/*; do
+    if [ ! -e "$file" ]; then
+      printf "Directory '%s' does not exist or does not contain any files.\nInstallation aborted.\n" "$HOME/.commit-tagger/hooks"
+      exit 1
+    fi
     fileName="$(basename "$file")"
     printf "Removing '%s'...\n" "$fileName"
     if ! rm "$hooksDir/$fileName"; then
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,4 +1,82 @@
 #!/bin/bash
 
-echo "running pre-commit!"
-#sleep 5
+hooksEnabled="$(git config --get commit-tagger.hooksenabled || printf "true")"
+testsEnabled="$(git config --get commit-tagger.testsenabled || printf "true")"
+testsVerbose="$(git config --get commit-tagger.testsverbose || printf "false")"
+
+if [ "$hooksEnabled" = "false" ]; then
+  exit 0
+elif [ "$hooksEnabled" != "true" ]; then
+  printf "Invalid option found: commit-tagger.hooksenabled=%s. Allowed values are true (default) and false.\n" "$hooksEnabled" >&2
+  printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
+  exit 1
+fi
+
+if [ "$testsEnabled" = "false" ]; then
+  exit 0
+elif [ "$testsEnabled" != "true" ]; then
+  printf "Invalid option found: commit-tagger.testsenabled=%s. Allowed values are true (default) and false.\n" "$testsEnabled" >&2
+  printf "Please use 'git config commit-tagger.testsenabled true|false' to set a valid configuration.\n" >&2
+  exit 1
+fi
+
+if [ "$testsVerbose" != "true" -a "$testsVerbose" != "false" ]; then
+  printf "Invalid option found: commit-tagger.testsverbose=%s. Allowed values are true and false (default).\n" "$testsVerbose" >&2
+  printf "Please use 'git config commit-tagger.testsverbose true|false' to set a valid configuration.\n" >&2
+  exit 1
+fi
+
+function runCommand {
+  # $@ = command
+
+  if [ "$failed" = "true" ]; then
+    return 1
+  fi
+  printf "Running: %s\n" "$*"
+  if [ "$testsVerbose" = "true" ]; then
+    $@
+  else
+    $@ > /dev/null 2>&1
+  fi
+  if [ $? = 0 ]; then
+    printf "Success: %s\n" "$*"
+    return 0
+  else
+    printf "Failed: %s\n" "$*"
+    failed="true"
+    return 1
+  fi
+}
+
+# Let's keep in our working directory only the staged files
+printf "Stashing unstaged files.\n\n"
+git stash save --keep-index --include-untracked --quiet 'commit-tagger: pre-commit test - unstaged files'
+if [ $? != 0 ]; then
+  printf "An error occurred while trying to save the working directory to a new stash.\n"
+  printf "Commit aborted.\n"
+  exit 1
+fi
+
+# trap cleanup EXIT
+# TODO: can't bash traps work in a hook?
+
+# Run your tests here!
+# runCommand gulp build:prod
+ runCommand test -n "hola"
+
+# Restore working directory
+printf "\nRestoring working directory from stash.\n"
+git stash pop --quiet
+if [ $? != 0 ]; then
+  printf "An error occurred while trying to restore the working directory from the saved stash.\n"
+  printf "Please try to run 'git stash pop' yourself.\n"
+  printf "Commit aborted.\n"
+  exit 1
+fi
+
+if [ "$failed" = "true" ]; then
+  printf "Commit aborted.\n"
+  exit 1
+else
+  exit 0
+fi
diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -37,7 +37,7 @@ function prompt {
   while true; do
     printf "%s" "$1"
     exec < /dev/tty
-    read promptRes
+    read -r promptRes
     case "$promptRes" in
       [yY]|[yY][eE][sS])
         return 0
@@ -55,12 +55,16 @@ function tagMessage {
   local str
   #str="$(echo "$1" | sed "1 s|^\([^\[].*\)$| \1|")"
   if [ "${1:0:1}" = "[" ]; then
-    str="$(git commit-tagger tag)$1"
+    str="$(git commit-tagger tag 2> /dev/null)$1"
   else
-    str="$(git commit-tagger tag) $1"
+    str="$(git commit-tagger tag 2> /dev/null) $1"
   fi
   if [ $? != 0 ]; then
-    exit 1
+    printf "\nError: commit-tagger cannot be found. Please re-install it or remove this hook from your repository.\n" >&2
+    printf "You can do so by deleting '%s'.\n" "$(git rev-parse --git-dir)/hooks/prepare-commit-msg" >&2
+    printf "If you continue with this commit it will not be tagged or affected in any way.\n\n" >&2
+    prompt "Do you wish to continue? [yes or no]: " >&2
+    exit $(($? + 1))
   fi
   printf "%s" "$str"
   return 0
@@ -71,14 +75,14 @@ case "$tagMode" in
     # if echo "$message" | head -1 | grep -q "^+"; then
     #   message="$(echo "$message" | sed "1 s|^+||")"
     if [ "${message:0:1}" = "+" ]; then
-      message="$(tagMessage "${message:1}")"
+      message="$(tagMessage "${message:1}")" || exit $(($? - 1))
     fi
   ;;
 
   "opt-out")
     # if echo "$message" | head -1 | grep -q -v "^-"; then
     if [ "${message:0:1}" != "-" ]; then
-      message="$(tagMessage "$message")"
+      message="$(tagMessage "$message")" || exit $(($? - 1))
     else
       # message="$(echo "$message" | sed "1 s|^-||")"
       message="${message:1}"
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -7,7 +7,7 @@ function prompt {
 
   while true; do
     printf "%s" "$1"
-    read promptRes
+    read -r promptRes
     case "$promptRes" in
       [yY]|[yY][eE][sS])
         return 0
@@ -23,27 +23,29 @@ function abortUninstall {
   # $1 = condition, $2 = message
 
   if [ $1 != 0 ]; then
-    printf "%s" "$2" >&2
+    printf "%s\n" "$2" >&2
     printf "Uninstallation aborted.\n" >&2
     exit 1
   fi
 }
 
 test -n "$installDir"
-abortUninstall $? "File '$HOME/.commit-tagger/installation_path' not found or empty.\n"
+abortUninstall $? "File '$HOME/.commit-tagger/installation_path' not found or empty."
 
 printf "You are about to uninstall 'commit-tagger'. The following files and folders will be permanently deleted:\n\n"
 printf "%s/git-commit-tagger\n" "$installDir"
 find "$HOME"/.commit-tagger
 printf "\n"
+printf "Warning: If you remove commit-tagger without previously removing all of its hooks from existing repositories\n"
+printf "errors will occur and you will have to delete said files manually.\n\n"
 prompt "Do you wish to continue? [yes or no]: "
 abortUninstall $?
 
 rm "$installDir"/git-commit-tagger &> /dev/null
-abortUninstall $? "Cannot delete '$installDir/git-commit-tagger'.\n"
+abortUninstall $? "Cannot delete '$installDir/git-commit-tagger'."
 
 rm -R "$HOME"/.commit-tagger &> /dev/null
-abortUninstall $? "An error occurred while deleting the contents of '$HOME/.commit-tagger'.\n"
+abortUninstall $? "An error occurred while deleting the contents of '$HOME/.commit-tagger'."
 
 printf "\nUninstallation successful.\n"
 exit 0
