[develop] Add uninstall, few improvements, fix prepare-commit-msg hook

diff --git a/git-commit-tagger b/git-commit-tagger
--- a/git-commit-tagger
+++ b/git-commit-tagger
@@ -53,7 +53,8 @@ function tag {
   parentExists=$?
   tagIgnored="$(git config --get commit-tagger.tagignored || printf "true")"
   if  [ "$tagIgnored" != "true" -a "$tagIgnored" != "false" ]; then
-    printf "Invalid option found: 'commit-tagger.tagignored=$tagIgnored'. Allowed values are true (default) and false.\nPlease use 'git config commit-tagger.tagignored true|false' to set a valid configuration.\n" >&2
+    printf "Invalid option found: 'commit-tagger.tagignored=$tagIgnored'. Allowed values are true (default) and false.\n" >&2
+    printf "Please use 'git config commit-tagger.tagignored true|false' to set a valid configuration.\n" >&2
     return 1
   fi
   if ! isIgnored $1 || [ "$tagIgnored" = "true" ]; then
@@ -73,9 +74,6 @@ function tag {
     fi
     printf "$tags\n"
     return 0
-  else
-    printf "Branch \e[1m$1\e[0m is currently being ignored.\n" >&2
-    return 1
   fi
 }
 
@@ -113,8 +111,7 @@ function get-parent {
 # -------- set-parent --------
 
 function set-parent {
-  # $1 = branch
-  # $2 = parentBranch
+  # $1 = branch, $2 = parentBranch
 
   local parent
   local counter
@@ -197,6 +194,7 @@ function ignore {
 
 # -------- /ignore --------
 
+
 # -------- unignore --------
 
 function unignore {
@@ -230,7 +228,7 @@ function install-hooks {
   local fileName
   hooksDir="$(git rev-parse --git-dir)/hooks"
   printf "Repository's Hooks directory: $hooksDir\n\n"
-  for file in ~/.commit-tagger/hooks/*; do
+  for file in "$HOME"/.commit-tagger/hooks/*; do
     fileName="$(basename "$file")"
     printf "Installing '$fileName'...\n"
     if ! cp "$file" "$hooksDir"; then
@@ -249,6 +247,29 @@ function install-hooks {
 # -------- /install-hooks --------
 
 
+# -------- uninstall-hooks --------
+
+function uninstall-hooks {
+  local hooksDir
+  local file
+  local fileName
+  hooksDir="$(git rev-parse --git-dir)/hooks"
+  printf "Repository's Hooks directory: $hooksDir\n\n"
+  for file in "$HOME"/.commit-tagger/hooks/*; do
+    fileName="$(basename "$file")"
+    printf "Removing '$fileName'...\n"
+    if ! rm "$hooksDir/$fileName"; then
+      printf "There was a problem removing '$fileName' from '$hooksDir'.\n" >&2
+      return 1
+    fi
+  done
+  printf "\nHooks successfully uninstalled.\n"
+  return 0
+}
+
+# -------- /uninstall-hooks --------
+
+
 # -------- usage --------
 
 function usage {
@@ -263,6 +284,7 @@ Available commands:
   ignore [<branch> [<branch> ...]]
   unignore [<branch> [<branch> ...]]
   install-hooks
+  uninstall-hooks
   help
 
 Commands description:
@@ -275,19 +297,24 @@ Commands description:
                     Branches created with <branch> as base won't automatically have <branch> set as parent.
   unignore          No longer ignore <branch>, or the current branch if omitted.
   install-hooks     Install commit-tagger's hooks into the current git repository.
+  uninstall-hooks   Remove commit-tagger's hooks from the current git repository.
   help              Show this message.
 
 Configuration:
   git config commit-tagger.<setting> <value>
 
 Available settings:
-  hooksenabled
-  checkoutenabled
-  commitmsgenabled
-  testenabled
-  tagignored
-  mode
-  confirm
+  hooksenabled      [true|false] Enable all of commit-tagger's hooks in this repository. Default: true.
+  checkoutenabled   [true|false] Enable the 'post-checkout' hook. Default true.
+  commitmsgenabled  [true|false] Enable the 'prepare-commit-msg' hook to tag messages. Default true.
+  testsenabled      [true|false] Enable the 'pre-commit' hook to test the files to be commited. Default: true.
+  testsverbose      [true|false] Show the output of all the tests. Default: false.
+  tagignored        [true|false] Tag commit messages on ignored branches. Default: true.
+  confirm           [true|false] Ask for confirmation before actually issuing the commit.
+                    Only when -m of -F is used. Default: true
+  tagMode           [opt-in|opt-out] Default: opt-out.
+                    opt-in: Do not tag commit messages unless prefixed with a "+" symbol.
+                    opt-out: Tag all commit messages automatically unless prefixed with a "-" symbol.
 EOF
 }
 
@@ -298,11 +325,12 @@ EOF
 
 function checkArgs {
   # $1 = min, $2 = max, $3 = argc, $4+ = argv
+
   if [ $3 -lt $1 ]; then
-    printf "Missing required argument for command '$4'.\nPlease run 'git commit-tagger help' to see the list of available commands\n" >&2
+    printf "Missing required arguments for command '$4'.\nPlease run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   elif [ $3 -gt $2 ]; then
-    printf "Invalid arguments: '${@:5}' for command '$4'.\nPlease run 'git commit-tagger help' to see the list of available commands\n" >&2
+    printf "Invalid arguments: '${@:5}' for command '$4'.\nPlease run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   fi
 }
@@ -373,6 +401,12 @@ case "$1" in
     install-hooks
   ;;
 
+  # uninstall-hooks
+  "uninstall-hooks")
+    checkArgs 1 1 $# $@
+    uninstall-hooks
+  ;;
+
   # help
   "help")
     checkArgs 1 1 $# $@
@@ -387,7 +421,7 @@ case "$1" in
 
   # invalid command
   *)
-    printf "Invalid command: '$1'.\nPlease run 'git commit-tagger help' to see the list of available commands\n" >&2
+    printf "Invalid command: '$1'.\nPlease run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   ;;
 esac
diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -1,160 +1,121 @@
 #!/bin/sh
 
-echo "hook!"
+#$1 = filename that contains the message, $2 = source of the commit message
 
 message="$(cat $1)"
 branch="$(git rev-parse --abbrev-ref HEAD)"
-getParent="$(git rev-parse --git-dir)/get-branch-parent"
-mode="$(git config --get commit-tagger.mode || echo "opt-out")"
-confirm="$(git config --get commit-tagger.confirm || echo "true")"
-hookEnabled="$(git config --get commit-tagger.enabled || echo "true")"
 
-if [ "$hookEnabled" = "false" ]; then
+hooksEnabled="$(git config --get commit-tagger.hooksenabled || echo "true")"
+commitmsgEnabled="$(git config --get commit-tagger.commitmsgenabled || echo "true")"
+tagIgnored="$(git config --get commit-tagger.tagignored || echo "true")"
+confirm="$(git config --get commit-tagger.confirm || echo "true")"
+tagMode="$(git config --get commit-tagger.tagmode || echo "opt-out")"
+
+if [ -n "$2" -a  "$2" != "message" ]; then
   exit 0
-elif [ "$hookEnabled" != "true" ]; then
-  echo -e "Invalid option found: commit-tagger.enabled=$hookEnabled. Allowed values are true (default) and false.\nPlease use 'git config commit-tagger.enabled true|false' to set a valid configuration."
+fi
+
+if [ "$hooksEnabled" = "false" ]; then
+  exit 0
+elif [ "$hooksEnabled" != "true" ]; then
+  printf "Invalid option found: commit-tagger.hooksenabled=$hooksEnabled. Allowed values are true (default) and false.\n" >&2
+  printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
   exit 1
 fi
 
-echo "start..."
-
-parents="$(cat "$(git rev-parse --git-dir)/branch-parents")"
-
-function catgetParent {
-  catParent="$(echo "$parents" | sed -n "s|$1:||p" | head -1)"
-  if [ ! -z "$catParent" ]; then
-    echo "$catParent"
-  else
-    return 1
-  fi
-}
-
-getParent="catgetParent"
+if [ "$commitmsgEnabled" = "false" ]; then
+  exit 0
+elif [ "$commitmsgEnabled" != "true" ]; then
+  printf "Invalid option found: commit-tagger.commitmsgenabled=$commitmsgEnabled. Allowed values are true (default) and false.\n" >&2
+  printf "Please use 'git config commit-tagger.commitmsgenabled true|false' to set a valid configuration.\n" >&2
+  exit 1
+fi
 
 function prompt {
-  case "$confirm" in
-    "true" )
-      formatMessage="$(echo "$message" | sed "s|^|  |")"
-      echo -e "The commit message will be the following:\n\n$formatMessage\n\n"
-       while true; do
-        echo -n -e "Do you wish to continue? [yes or no]: "
+  # $1 = message
 
-        exec < /dev/tty
-        read promptRes
-        case "$promptRes" in
-          [yY] | [yY][eE][sS] )
-            return 0
-            ;;
-
-          [nN] | [nN][oO] )
-            return 1
-            ;;
-        esac
-       done
+  while true; do
+    printf "$1"
+    exec < /dev/tty
+    read promptRes
+    case "$promptRes" in
+      [yY]|[yY][eE][sS])
+        return 0
       ;;
-
-    "false" )
-      return 0
+      [nN]|[nN][oO])
+        return 1
       ;;
-
-    * )
-      echo -e "Invalid option found: commit-tagger.confirm=$confirm. Allowed values are true (default) and false.\nPlease use 'git config commit-tagger.confirm true|false' to set a valid configuration."
-      exit 1
-      ;;
-  esac
-}
-
-function getTag {
-  echo "$(echo $1 | sed "s|.*\/||")"
+    esac
+  done
 }
 
 function tagMessage {
-  parentBranch="$("$getParent" "$branch")"
-  parentExists=$?
-  if [ "$parentExists" -eq 0 ]; then
-    if [ "$parentBranch" != "--ignore" ]; then
-      message="$(echo "$message" | sed "1 s|^\([^\[].*\)$| \1|")"
-      message="[$(getTag "$branch")]$message"
+  # $1 = message
 
-      counter=20
-      while [ "$parentExists" -eq 0 -a "$parentBranch" != "--ignore" ]; do
-        message="[$(getTag "$parentBranch")]$message"
-        parentBranch="$("$getParent" "$parentBranch")"
-        parentExists=$?
-        echo "$parentBranch"
-        counter=$(($counter - 1))
-        if [ $counter -lt 0 ]; then
-          echo -e "Sorry, there seems to be an error in the branch hierarchy causing an infinite loop."
-          exit 1
-        fi
-      done
-    fi
+  local str
+  #str="$(echo "$1" | sed "1 s|^\([^\[].*\)$| \1|")"
+  if [ "${1:0:1}" = "[" ]; then
+    str="$(git commit-tagger tag)$1"
   else
-    message="$(echo "$message" | sed "1 s|^\([^\[].*\)$| \1|")"
-    message="[$(getTag "$branch")]$message"
+    str="$(git commit-tagger tag) $1"
   fi
+  if [ $? != 0 ]; then
+    exit 1
+  fi
+  printf "$str"
+  return 0
 }
 
-echo "end of functions"
-
-case "$mode" in
+case "$tagMode" in
   "opt-in" )
-    if echo "$message" | head -1 | grep -q "^+"; then
-      message="$(echo "$message" | sed "1 s|^+||")"
-      tagMessage
+    # if echo "$message" | head -1 | grep -q "^+"; then
+    #   message="$(echo "$message" | sed "1 s|^+||")"
+    if [ "${message:0:1}" = "+" ]; then
+      message="$(tagMessage "${message:1}")"
     fi
   ;;
 
   "opt-out" )
-    if echo "$message" | head -1 | grep -q -v "^-"; then
-      echo "tag"
-      tagMessage
-      echo "tagged"
+    # if echo "$message" | head -1 | grep -q -v "^-"; then
+    if [ "${message:0:1}" != "-" ]; then
+      message="$(tagMessage "$message")"
     else
-      message="$(echo "$message" | sed "1 s|^-||")"
+      # message="$(echo "$message" | sed "1 s|^-||")"
+      message="${message:1}"
     fi
   ;;
 
   * )
-    echo -e "Invalid option found: commit-tagger.mode=$mode. Allowed values are opt-in and opt-out (default).\nPlease use 'git config commit-tagger.mode opt-in|opt-out' to set a valid configuration."
+    printf "Invalid option found: commit-tagger.tagmode=$tagMode. Allowed values are opt-in and opt-out (default).\n" >&2
+    printf "Please use 'git config commit-tagger.tagmode opt-in|opt-out' to set a valid configuration.\n" >&2
     exit 1
   ;;
 esac
 
-if [ "$2" != "message" ] || prompt; then
-  echo "$message" > $1
+if [ "$2" = "message" ]; then
+  case "$confirm" in
+    "true")
+      formatMessage="$(printf "$message" | sed "s|^|  |")"
+      printf "The commit message will be the following:\n\n$formatMessage\n\n\n"
+      prompt "Do you wish to continue? [yes or no]: "
+      if [ $? = 0 ]; then
+        printf "$message" > $1
+        exit 0
+      else
+        printf "The commit has been aborted."
+        exit 1
+      fi
+    ;;
+    "false")
+      printf "$message" > $1
+    ;;
+    *)
+      printf "Invalid option found: commit-tagger.confirm=$confirm. Allowed values are true (default) and false.\n" >&2
+      printf "Please use 'git config commit-tagger.confirm true|false' to set a valid configuration.\n" >&2
+      exit 1
+    ;;
+  esac
 else
-  echo -e "The commit has been aborted."
-  exit 1
+  printf "$message" > $1
+  exit 0
 fi
-
-
-# if ! echo "$message" | grep -q "^-"; then
-#   # message="$(echo "$message" | sed "s|^+\(+*\)\[|\1\[|" | sed "s|^\([^\[].*\)$| \1|")"
-
-#   if "$getParent" "$branch" > /dev/null; then
-#     if [ "$("$getParent" "$branch")" != "--ignore" ]; then
-#       message="$(echo "$message" | sed "1 s|^\([^\[].*\)$| \1|")"
-#       message="[$(getTag "$branch")]$message"
-
-#       counter=20
-#       while "$getParent" "$branch" > /dev/null && [ "$("$getParent" "$branch")" != "--ignore" ]; do
-#         message="[$(getTag "$("$getParent" "$branch")")]$message"
-#         branch="$("$getParent" "$branch")"
-#         counter=$(($counter - 1))
-#         if [ $counter -lt 0 ]; then
-#           echo -e "Sorry, there seems to be an error in the branch hierarchy causing an infinite loop."
-#           exit 1
-#         fi
-#       done
-#     fi
-#   else
-#     message="$(echo "$message" | sed "1 s|^\([^\[].*\)$| \1|")"
-#     message="[$(getTag "$branch")]$message"
-#   fi
-
-#   echo "$message" > $1
-# else
-#   message="$(echo "$message" | sed "1 s|^-||")"
-#   echo "$message" > $1
-# fi
diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,66 +2,83 @@
 
 # $1 = [optional] installation dir
 
+function prompt {
+  # $1 = message
+
+  while true; do
+    printf "$1"
+    read promptRes
+    case "$promptRes" in
+      [yY]|[yY][eE][sS])
+        return 0
+        ;;
+      [nN]|[nN][oO])
+        return 1
+        ;;
+    esac
+  done
+}
+
+function abortInstall {
+  # $1 = condition, $2 = message
+
+  if [ $1 != 0 ]; then
+    printf "$2" >&2
+    printf "Installation aborted.\n" >&2
+    exit 1
+  fi
+}
+
+test -f "git-commit-tagger"
+abortInstall $? "Cannot find 'git-commit-tagger'. Please make sure your working directory matches the install script's path.\n"
+
 if [ -n "$1" ]; then
   installDir="${1%%/}"
 else
-  installDir=~/bin
+  installDir="$HOME"/bin
   installDefault=true
 fi
 
-if [ "$installDefault" = true -a ! -d "$installDir" ]; then
-  mkdir "$installDir"
-  if [ $? != 0 ]; then
-    printf "There was a problem creating '$installDir'.\n" >&2
-    printf "Installation aborted.\n" >&2
-    exit 1
-  fi
-fi
-
 if [ ! -d "$installDir" ]; then
-  printf "Directory '$installDir' does not exist.\n" >&2
-  printf "Installation aborted.\n" >&2
-  exit 1
-fi
-
-if [ ! -f "git-commit-tagger" ]; then
-  printf "Cannot find 'git-commit-tagger'. Please make sure your working directory matches the install script's path.\n" >&2
-  printf "Installation aborted.\n" >&2
-  exit 1
+  if [ "$installDefault" != true ]; then
+    prompt "Directory '$installDir' does not exist. Do you wish to create it? [yes or no]: "
+    abortInstall $?
+  fi
+  printf "Creating directory '$installDir'.\n"
+  mkdir -p "$installDir" &> /dev/null
+  abortInstall $? "There was a problem creating '$installDir'.\n"
 fi
 
 printf "Installing 'git-commit-tagger' into '$installDir'.\n"
-cp git-commit-tagger "$installDir"
-if [ $? != 0 ]; then
-  printf "There was a problem copying 'git-commit-tagger' to '$installDir'.\n" >&2
-  printf "Installation aborted.\n" >&2
-  exit 1
-fi
+cp git-commit-tagger "$installDir" &> /dev/null
+abortInstall $? "There was a problem copying 'git-commit-tagger' to '$installDir'.\n"
 
 printf "Giving execute permissions to '$installDir/git-commit-tagger'.\n"
-chmod +x "$installDir"/git-commit-tagger
-if [ $? != 0 ]; then
-  printf "There was a problem giving execute permissions to '$installDir/git-commit-tagger'.\n" >&2
-  printf "Installation aborted.\n" >&2
-  exit 1
+chmod +x "$installDir"/git-commit-tagger &> /dev/null
+abortInstall $? "There was a problem giving execute permissions to '$installDir/git-commit-tagger'.\n"
+
+if [ ! -d "$HOME"/.commit-tagger ]; then
+  printf "Creating directory '$HOME/.commit-tagger'.\n"
+  mkdir "$HOME"/.commit-tagger &> /dev/null
+  abortInstall $? "There was a problem creating '$HOME/.commit-tagger'.\n"
 fi
 
-printf "Installing needed files into '$HOME/.commit-tagger'.\n"
-if [ ! -d ~/.commit-tagger ]; then
-  mkdir ~/.commit-tagger
-  if [ $? != 0 ]; then
-    printf "There was a problem creating '$HOME/.commit-tagger'.\n"
-    printf "Installation aborted.\n" >&2
-    exit 1
-  fi
+printf "Saving 'installation_path' to '$HOME/.commit-tagger'.\n"
+printf "$installDir" > "$HOME"/.commit-tagger/installation_path
+test -f "$HOME"/.commit-tagger/installation_path
+abortInstall $? "There was a problem creating '$HOME/.commit-tagger/hooks'.\n"
+
+if [ ! -d "$HOME"/.commit-tagger/hooks ]; then
+  printf "Creating directory '$HOME/.commit-tagger/hooks'.\n"
+  mkdir "$HOME"/.commit-tagger/hooks &> /dev/null
+  abortInstall $? "There was a problem creating '$HOME/.commit-tagger/hooks'.\n"
 fi
 
-cp -R hooks ~/.commit-tagger
-if [ $? != 0 ]; then
-  printf "There was a problem copying 'hooks' into '$HOME/.commit-tagger'.\n"
-  printf "Installation aborted.\n" >&2
-  exit 1
-fi
+for file in hooks/*; do
+  printf "Copying '$file' into '"$HOME"/.commit-tagger/hooks'.\n"
+  cp "$file" "$HOME"/.commit-tagger/hooks &> /dev/null
+  abortInstall $? "There was a problem copying '$file' into '$HOME/.commit-tagger/hooks'.\n"
+done
 
 printf "\nInstallation successful.\n"
 exit 0
