[develop] Pre-commit hook, improve uninstall-hooks

diff --git a/git-commit-tagger b/git-commit-tagger
--- a/git-commit-tagger
+++ b/git-commit-tagger
@@ -28,6 +28,23 @@ function isIgnored {
   return $?
 }
 
+function prompt {
+  # $1 = message
+
+  while true; do
+    printf "%s" "$1"
+    read -r promptRes
+    case "$promptRes" in
+      [yY]|[yY][eE][sS])
+        return 0
+      ;;
+      [nN]|[nN][oO])
+        return 1
+      ;;
+    esac
+  done
+}
+
 # -------- /general --------
 
 
@@ -226,22 +243,42 @@ function install-hooks {
   local hooksDir
   local file
   local fileName
+  local replaceFiles
   hooksDir="$(git rev-parse --git-dir)/hooks"
   printf "Repository's Hooks directory: %s\n\n" "$hooksDir"
-  for file in "$HOME"/.commit-tagger/hooks/*; do
+  for file in "$HOME/.commit-tagger/hooks"/*; do
+    fileName="$(basename "$file")";
+    if [ -e "$hooksDir/$fileName" ]; then
+      replaceFiles="true"
+      printf "File '%s/%s' already exists.\n" "$hooksDir" "$fileName"
+    fi
+  done
+  if [ "$replaceFiles" = "true" ]; then
+    printf "\nIf you continue those files will be replaced.\n"
+    prompt "Do you wish to continue? [yes or no]: "
+    if [ $? != 0 ]; then
+      printf "\nInstallation aborted.\n"
+      exit 1
+    fi
+    printf "\n"
+  fi
+  for file in "$HOME/.commit-tagger/hooks"/*; do
     if [ ! -e "$file" ]; then
-      printf "Directory '%s' does not exist or does not contain any files.\nInstallation aborted.\n" "$HOME/.commit-tagger/hooks"
+      printf "Directory '%s' does not exist or does not contain any files.\n" "$HOME/.commit-tagger/hooks" >&2
+      printf "Installation aborted.\n"
       exit 1
     fi
     fileName="$(basename "$file")"
     printf "Installing '%s'...\n" "$fileName"
     if ! cp "$file" "$hooksDir"; then
       printf "There was a problem copying '%s' to '%s'.\n" "$file" "$hooksDir" >&2
-      return 1
+      printf "Installation aborted.\n"
+      exit 1
     fi
     if ! chmod +x "$hooksDir/$fileName"; then
       printf "There was a problem giving execute permissions to '%s/%s'.\n" "$hooksDir" "$fileName" >&2
-      return 1
+      printf "Installation aborted.\n"
+      exit 1
     fi
   done
   printf "\nHooks successfully installed.\n"
@@ -259,16 +296,22 @@ function uninstall-hooks {
   local fileName
   hooksDir="$(git rev-parse --git-dir)/hooks"
   printf "Repository's Hooks directory: %s\n\n" "$hooksDir"
-  for file in "$HOME"/.commit-tagger/hooks/*; do
+  for file in "$HOME/.commit-tagger/hooks"/*; do
     if [ ! -e "$file" ]; then
-      printf "Directory '%s' does not exist or does not contain any files.\nInstallation aborted.\n" "$HOME/.commit-tagger/hooks"
+      printf "Directory '%s' does not exist or does not contain any files.\n" "$HOME/.commit-tagger/hooks" >&2
+      printf "Installation aborted.\n"
       exit 1
     fi
     fileName="$(basename "$file")"
+    if [ ! -e "$hooksDir/$fileName" ]; then
+      printf "File '%s' not found.\n" "$hooksDir/$fileName" >&2
+      continue
+    fi
     printf "Removing '%s'...\n" "$fileName"
     if ! rm "$hooksDir/$fileName"; then
       printf "There was a problem removing '%s' from '%s'.\n" "$fileName" "$hooksDir" >&2
-      return 1
+      printf "Installation aborted.\n"
+      exit 1
     fi
   done
   printf "\nHooks successfully uninstalled.\n"
@@ -335,10 +378,12 @@ function checkArgs {
   # $1 = min, $2 = max, $3 = argc, $4+ = argv
 
   if [ $3 -lt $1 ]; then
-    printf "Missing required arguments for command '%s'.\nPlease run 'git commit-tagger help' to see the list of available commands.\n" "$4" >&2
+    printf "Missing required arguments for command '%s'.\n" "$4" >&2
+    printf "Please run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   elif [ $3 -gt $2 ]; then
-    printf "Invalid arguments: '%s' for command '%s'.\nPlease run 'git commit-tagger help' to see the list of available commands.\n" "${@:5}" "$4" >&2
+    printf "Invalid arguments: '%s' for command '%s'.\n" "${@:5}" "$4" >&2
+    printf "Please run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   fi
 }
@@ -429,7 +474,8 @@ case "$1" in
 
   # invalid command
   *)
-    printf "Invalid command: '%s'.\nPlease run 'git commit-tagger help' to see the list of available commands.\n" "$1" >&2
+    printf "Invalid command: '%s'.\n" "$1" >&2
+    printf "Please run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   ;;
 esac
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+#
+# Please enter your custom pre-commit commands at the bottom of this file
+#
+
 hooksEnabled="$(git config --get commit-tagger.hooksenabled || printf "true")"
 testsEnabled="$(git config --get commit-tagger.testsenabled || printf "true")"
 testsVerbose="$(git config --get commit-tagger.testsverbose || printf "false")"
@@ -9,6 +13,7 @@ if [ "$hooksEnabled" = "false" ]; then
 elif [ "$hooksEnabled" != "true" ]; then
   printf "Invalid option found: commit-tagger.hooksenabled=%s. Allowed values are true (default) and false.\n" "$hooksEnabled" >&2
   printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
+  printf "Commit aborted.\n"
   exit 1
 fi
 
@@ -17,66 +22,124 @@ if [ "$testsEnabled" = "false" ]; then
 elif [ "$testsEnabled" != "true" ]; then
   printf "Invalid option found: commit-tagger.testsenabled=%s. Allowed values are true (default) and false.\n" "$testsEnabled" >&2
   printf "Please use 'git config commit-tagger.testsenabled true|false' to set a valid configuration.\n" >&2
+  printf "Commit aborted.\n"
   exit 1
 fi
 
 if [ "$testsVerbose" != "true" -a "$testsVerbose" != "false" ]; then
   printf "Invalid option found: commit-tagger.testsverbose=%s. Allowed values are true and false (default).\n" "$testsVerbose" >&2
   printf "Please use 'git config commit-tagger.testsverbose true|false' to set a valid configuration.\n" >&2
+  printf "Commit aborted.\n"
   exit 1
 fi
 
+exec 0< /dev/tty 1> /dev/tty 2>&1
+
 function runCommand {
-  # $@ = command
+  # $1 = command, $2 = [display name]
 
   if [ "$failed" = "true" ]; then
     return 1
   fi
-  printf "Running: %s\n" "$*"
-  if [ "$testsVerbose" = "true" ]; then
-    $@
+  if [ -n "$2" ]; then
+    displayName="$2"
   else
-    $@ > /dev/null 2>&1
+    displayName="$1"
+  fi
+  printf "Starting '\e[1m%s\e[0m'...\n" "$displayName"
+  if [ "$testsVerbose" = "true" ]; then
+    eval "$1"
+  else
+    eval "$1" > /dev/null 2>&1
   fi
   if [ $? = 0 ]; then
-    printf "Success: %s\n" "$*"
+    printf "Finished '\e[1m%s\e[0m' successfully.\n" "$displayName"
     return 0
   else
-    printf "Failed: %s\n" "$*"
-    failed="true"
-    return 1
+    printf "Failed: '\e[1m%s\e[0m'.\n" "$displayName"
+    printf "Commit aborted.\n"
+    exit 1
   fi
 }
 
-# Let's keep in our working directory only the staged files
-printf "Stashing unstaged files.\n\n"
-git stash save --keep-index --include-untracked --quiet 'commit-tagger: pre-commit test - unstaged files'
-if [ $? != 0 ]; then
-  printf "An error occurred while trying to save the working directory to a new stash.\n"
-  printf "Commit aborted.\n"
-  exit 1
-fi
+function stashSave {
+  local prevStashRef
+  prevStashRef="$(git show-ref --hash stash)"
+  git stash save --keep-index --include-untracked 'commit-tagger: pre-commit test - unstaged files' > /dev/null 2>&1
+  if [ $? != 0 ]; then
+    printf "An error occurred while trying to save the working directory to a new stash and remove unstaged files.\n" >&2
+    printf "Commit aborted.\n"
+    exit 1
+  fi
+  if [ "$(git show-ref --hash stash)" != "$prevStashRef" ]; then
+    stashedChanges="true"
+    printf "Stashed unstaged files.\n\n"
+  fi
+  return 0
+}
 
-# trap cleanup EXIT
-# TODO: can't bash traps work in a hook?
+function stashPop {
+  if [ "$stashedChanges" != "true" ]; then
+    return 0
+  fi
+  git reset --hard HEAD > /dev/null 2>&1
+  if [ $? != 0 ]; then
+    printf "An error occurred while trying to reset the working directory.\n" >&2
+    printf "Please check 'git stash list' and run 'git reset --hard HEAD' and 'git stash pop' yourself.\n" >&2
+    printf "Commit aborted.\n"
+    exit 1
+  fi
+  git stash pop --index > /dev/null 2>&1
+  if [ $? != 0 ]; then
+    printf "An error occurred while trying to restore the working directory from the saved stash.\n" >&2
+    printf "Please check 'git stash list' and run 'git stash pop' yourself.\n" >&2
+    printf "Commit aborted.\n"
+    exit 1
+  fi
+  stashedChanges="false"
+  printf "\nRestored working directory from stash.\n"
+  return 0
+}
 
-# Run your tests here!
-# runCommand gulp build:prod
- runCommand test -n "hola"
+function interrupt {
+  printf "\nCommit aborted.\n"
+  printf "Working directory will be restored from stash.\n"
+  exec 1> /dev/null
+  trap - INT
+  kill -INT $$
+}
 
-# Restore working directory
-printf "\nRestoring working directory from stash.\n"
-git stash pop --quiet
-if [ $? != 0 ]; then
-  printf "An error occurred while trying to restore the working directory from the saved stash.\n"
-  printf "Please try to run 'git stash pop' yourself.\n"
-  printf "Commit aborted.\n"
-  exit 1
-fi
 
-if [ "$failed" = "true" ]; then
-  printf "Commit aborted.\n"
-  exit 1
-else
-  exit 0
-fi
+stashSave
+trap "stashPop" EXIT
+trap "interrupt" INT
+
+
+# Run your commands here!
+# Syntax: runCommand "<command>" ["<displayName>"]
+# if <displayName> is omitted, <command> will be shown instead.
+#
+# Example:
+#
+# runCommand "gulp build:prod" "production build"
+# runCommand "gulp jscs"
+#
+# This will output something like:
+#   Starting 'production build'...
+#   < command output >
+#   Finished 'production build' successfully.
+#   Starting 'gulp jscs'
+#   < command output >
+#   Failed: 'gulp jscs'
+#   Commit aborted.
+#
+# Remember you can use 'git config commit-tagger.testsverbose true|false'
+# to show or hide commands output.
+#
+# Please be careful not to omit 'runCommand'.
+
+printf "  You can run your own commands and tests in here.\n"
+printf "  Only changes in the index will be taken into account.\n"
+printf "  Unstaged files will be stashed and automatically restored later.\n"
+
+exit 0
