[develop] Improve cross platform compatibility, add local repository check, minor readability changes

diff --git a/git-commit-tagger b/git-commit-tagger
--- a/git-commit-tagger
+++ b/git-commit-tagger
@@ -3,6 +3,11 @@
 
 # -------- general --------
 
+if ! git rev-parse --git-dir > /dev/null 2>&1; then
+  printf "Error: Current directory (or any of the parent directories) is not a git repository.\n"
+  exit 1
+fi
+
 parentsFile="$(git rev-parse --git-dir)/commit-tagger.parents"
 ignoredFile="$(git rev-parse --git-dir)/commit-tagger.ignored"
 parents="$(cat "$parentsFile" 2> /dev/null)"
@@ -68,10 +73,10 @@ ctTag () {
   local tagIgnored
   parent="$(getParent "$1")"
   parentExists=$?
-  tagIgnored="$(git config --get commit-tagger.tagignored || printf "true")"
+  tagIgnored="$(git config --get commit-tagger.tagIgnored || printf "true")"
   if  [ "$tagIgnored" != "true" -a "$tagIgnored" != "false" ]; then
-    printf "Invalid option found: 'commit-tagger.tagignored=%s'. Allowed values are true (default) and false.\n" "$tagIgnored" >&2
-    printf "Please use 'git config commit-tagger.tagignored true|false' to set a valid configuration.\n" >&2
+    printf "Invalid option found: 'commit-tagger.tagIgnored=%s'. Allowed values are true (default) and false.\n" "$tagIgnored" >&2
+    printf "Please use 'git config commit-tagger.tagIgnored true|false' to set a valid configuration.\n" >&2
     return 1
   fi
   if ! isIgnored $1 || [ "$tagIgnored" = "true" ]; then
@@ -384,17 +389,17 @@ Configuration:
   git config commit-tagger.<setting> <value>
 
 Available settings:
-  hooksenabled      [true|false] Enable all of commit-tagger's hooks in this repository. Default: true.
-  checkoutenabled   [true|false] Enable the 'post-checkout' hook. Default true.
-  commitmsgenabled  [true|false] Enable the 'prepare-commit-msg' hook to tag messages. Default true.
-  precommitenabled  [true|false] Enable the 'pre-commit' hook to test the files to be commited. Default: true.
-  precommitverbose  [true|false] Show the output of all the tests. Default: false.
-  tagignored        [true|false] Tag commit messages on ignored branches. Default: true.
-  confirm           [true|false] Ask for confirmation before actually issuing the commit.
-                    Only when -m of -F is used. Default: true
-  tagMode           [opt-in|opt-out] Default: opt-out.
-                    opt-in: Do not tag commit messages unless prefixed with a "+" symbol.
-                    opt-out: Tag all commit messages automatically unless prefixed with a "-" symbol.
+  hooksEnabled      (true|false) Enable all commit-tagger's hooks in this repository. Default: true.
+  checkoutEnabled   (true|false) Enable the 'post-checkout' hook. Default true.
+  commitMsgEnabled  (true|false) Enable the 'prepare-commit-msg' hook to tag messages. Default true.
+  preCommitEnabled  (true|false) Enable the 'pre-commit' hook to run custom commands. Default: true.
+  preCommitVerbose  (true|false) Show the output of all the tests. Default: false.
+  tagIgnored        (true|false) Tag commit messages on ignored branches. Default: true.
+  confirm           (true|false) Ask for confirmation before actually issuing the commit.
+                    Only when -m or -F is used. Default: true.
+  tagMode           (opt-in|opt-out) Default: opt-out.
+                    opt-in: Do not tag commit messages unless prefixed with a "+".
+                    opt-out: Tag all commit messages automatically unless prefixed with a "-".
 EOF
 }
 
@@ -406,15 +411,29 @@ EOF
 checkArgs () {
   # $1 = min, $2 = max, $3 = argc, $4+ = argv
 
-  if [ $3 -lt $1 ]; then
-    printf "Missing required arguments for command '%s'.\n" "$4" >&2
+  local min
+  local max
+  local argc
+  local comm
+  local args
+  min="$1"
+  max="$2"
+  argc="$3"
+  comm="$4"
+  shift 4
+  args="$@"
+  if [ "$argc" -lt "$min" ]; then
+    printf "Missing required arguments for command '%s'.\n" "$comm" >&2
     printf "Please run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
-  elif [ $3 -gt $2 ]; then
-    printf "Invalid arguments: '%s' for command '%s'.\n" "${@:5}" "$4" >&2
+  elif [ "$argc" -gt "$max" ]; then
+    printf "Invalid arguments: '%s' for command '%s'.\n" "$args" "$comm" >&2
     printf "Please run 'git commit-tagger help' to see the list of available commands.\n" >&2
     exit 1
   fi
+
+  # bash only:
+  # ${@:5} = shift 4; $@
 }
 
 case "$1" in
@@ -518,5 +537,7 @@ case "$1" in
     exit 1
   ;;
 esac
+
+exit $?
 
 # -------- /main --------
diff --git a/hooks/post-checkout b/hooks/post-checkout
--- a/hooks/post-checkout
+++ b/hooks/post-checkout
@@ -5,22 +5,22 @@
 prevHEAD="$1"
 newHEAD="$2"
 checkoutType="$3"
-hooksEnabled="$(git config --get commit-tagger.hooksenabled || printf "true")"
-checkoutEnabled="$(git config --get commit-tagger.checkoutenabled || printf "true")"
+hooksEnabled="$(git config --get commit-tagger.hooksEnabled || printf "true")"
+checkoutEnabled="$(git config --get commit-tagger.checkoutEnabled || printf "true")"
 
 if [ "$hooksEnabled" = "false" ]; then
   exit 0
 elif [ "$hooksEnabled" != "true" ]; then
-  printf "Invalid option found: commit-tagger.hooksenabled=$hooksEnabled. Allowed values are true (default) and false.\n" >&2
-  printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.hooksEnabled=$hooksEnabled. Allowed values are true (default) and false.\n" >&2
+  printf "Please use 'git config commit-tagger.hooksEnabled true|false' to set a valid configuration.\n" >&2
   exit 1
 fi
 
 if [ "$checkoutEnabled" = "false" ]; then
   exit 0
 elif [ "$checkoutEnabled" != "true" ]; then
-  printf "Invalid option found: commit-tagger.hooksenabled=$checkoutEnabled. Allowed values are true (default) and false.\n" >&2
-  printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.checkoutEnabled=$checkoutEnabled. Allowed values are true (default) and false.\n" >&2
+  printf "Please use 'git config commit-tagger.checkoutEnabled true|false' to set a valid configuration.\n" >&2
   exit 1
 fi
 
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,15 +1,15 @@
 #!/bin/bash
 
-hooksEnabled="$(git config --get commit-tagger.hooksenabled || printf "true")"
-preCommitEnabled="$(git config --get commit-tagger.precommitenabled || printf "true")"
-preCommitVerbose="$(git config --get commit-tagger.precommitverbose || printf "false")"
+hooksEnabled="$(git config --get commit-tagger.hooksEnabled || printf "true")"
+preCommitEnabled="$(git config --get commit-tagger.preCommitEnabled || printf "true")"
+preCommitVerbose="$(git config --get commit-tagger.preCommitVerbose || printf "false")"
 commandsFile="$(git rev-parse --git-dir)/commit-tagger.precommit"
 
 if [ "$hooksEnabled" = "false" ]; then
   exit 0
 elif [ "$hooksEnabled" != "true" ]; then
-  printf "Invalid option found: commit-tagger.hooksenabled=%s. Allowed values are true (default) and false.\n" "$hooksEnabled" >&2
-  printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.hooksEnabled=%s. Allowed values are true (default) and false.\n" "$hooksEnabled" >&2
+  printf "Please use 'git config commit-tagger.hooksEnabled true|false' to set a valid configuration.\n" >&2
   printf "Commit aborted.\n"
   exit 1
 fi
@@ -17,15 +17,15 @@ fi
 if [ "$preCommitEnabled" = "false" ]; then
   exit 0
 elif [ "$preCommitEnabled" != "true" ]; then
-  printf "Invalid option found: commit-tagger.precommitenabled=%s. Allowed values are true (default) and false.\n" "$preCommitEnabled" >&2
-  printf "Please use 'git config commit-tagger.precommitenabled true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.preCommitEnabled=%s. Allowed values are true (default) and false.\n" "$preCommitEnabled" >&2
+  printf "Please use 'git config commit-tagger.preCommitEnabled true|false' to set a valid configuration.\n" >&2
   printf "Commit aborted.\n"
   exit 1
 fi
 
 if [ "$preCommitVerbose" != "true" -a "$preCommitVerbose" != "false" ]; then
-  printf "Invalid option found: commit-tagger.precommitverbose=%s. Allowed values are true and false (default).\n" "$preCommitVerbose" >&2
-  printf "Please use 'git config commit-tagger.precommitverbose true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.preCommitVerbose=%s. Allowed values are true and false (default).\n" "$preCommitVerbose" >&2
+  printf "Please use 'git config commit-tagger.preCommitVerbose true|false' to set a valid configuration.\n" >&2
   printf "Commit aborted.\n"
   exit 1
 fi
diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -5,11 +5,10 @@
 message="$(cat $1)"
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-hooksEnabled="$(git config --get commit-tagger.hooksenabled || printf "true")"
-commitmsgEnabled="$(git config --get commit-tagger.commitmsgenabled || printf "true")"
-tagIgnored="$(git config --get commit-tagger.tagignored || printf "true")"
+hooksEnabled="$(git config --get commit-tagger.hooksEnabled || printf "true")"
+commitmsgEnabled="$(git config --get commit-tagger.commitMsgEnabled || printf "true")"
 confirm="$(git config --get commit-tagger.confirm || printf "true")"
-tagMode="$(git config --get commit-tagger.tagmode || printf "opt-out")"
+tagMode="$(git config --get commit-tagger.tagMode || printf "opt-out")"
 
 if [ -n "$2" -a "$2" != "message" ]; then
   exit 0
@@ -18,16 +17,16 @@ fi
 if [ "$hooksEnabled" = "false" ]; then
   exit 0
 elif [ "$hooksEnabled" != "true" ]; then
-  printf "Invalid option found: commit-tagger.hooksenabled=%s. Allowed values are true (default) and false.\n" "$hooksEnabled" >&2
-  printf "Please use 'git config commit-tagger.hooksenabled true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.hooksEnabled=%s. Allowed values are true (default) and false.\n" "$hooksEnabled" >&2
+  printf "Please use 'git config commit-tagger.hooksEnabled true|false' to set a valid configuration.\n" >&2
   exit 1
 fi
 
 if [ "$commitmsgEnabled" = "false" ]; then
   exit 0
 elif [ "$commitmsgEnabled" != "true" ]; then
-  printf "Invalid option found: commit-tagger.commitmsgenabled=%s. Allowed values are true (default) and false.\n" "$commitmsgEnabled" >&2
-  printf "Please use 'git config commit-tagger.commitmsgenabled true|false' to set a valid configuration.\n" >&2
+  printf "Invalid option found: commit-tagger.commitMsgEnabled=%s. Allowed values are true (default) and false.\n" "$commitmsgEnabled" >&2
+  printf "Please use 'git config commit-tagger.commitMsgEnabled true|false' to set a valid configuration.\n" >&2
   exit 1
 fi
 
@@ -64,7 +63,7 @@ tagMessage () {
     printf "\nError: commit-tagger cannot be found. Please re-install it or remove this hook from your repository.\n" >&2
     printf "You can do so by deleting '%s'.\n" "$(git rev-parse --git-dir)/hooks/prepare-commit-msg" >&2
     printf "If you continue with this commit it will not be tagged or affected in any way.\n\n" >&2
-    prompt "Do you wish to continue? [yes or no]: " >&2
+    prompt "Do you wish to continue? [yes or no]: "
     exit $(($? + 1))
   fi
   printf "%s" "$str"
@@ -91,8 +90,8 @@ case "$tagMode" in
   ;;
 
   *)
-    printf "Invalid option found: commit-tagger.tagmode=%s. Allowed values are opt-in and opt-out (default).\n" "$tagMode" >&2
-    printf "Please use 'git config commit-tagger.tagmode opt-in|opt-out' to set a valid configuration.\n" >&2
+    printf "Invalid option found: commit-tagger.tagMode=%s. Allowed values are opt-in and opt-out (default).\n" "$tagMode" >&2
+    printf "Please use 'git config commit-tagger.tagMode opt-in|opt-out' to set a valid configuration.\n" >&2
     exit 1
   ;;
 esac
